name: "build"
on: [push, pull_request]
jobs:
  launch-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Build Images
        run: |
          ./build.sh
      - name: Run the notebooks
        run: |
          cd 01-MachineLearning
          pip3 install -r requirements.txt
          pip3 install jupyter
          for f in *.c; 
            do echo "Processing $f file..";
            jupyter nbconvert --execute --to notebook --inplace $f
          done
