name: "build"
on: [push, pull_request]
jobs:
  launch-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Run the notebooks
        run: |
          cd 01-MachineLearning
          pip3 install -r requirements.txt
          pip3 install jupyter
          for f in *.ipynb; 
            do echo "Processing $f file...";
            jupyter nbconvert --execute --to notebook --inplace $f
            jupyter nbconvert --to script $f
            extension="${f##*.}"
            filename="${f%.*}"
            # echo -e "from IPython import get_ipython\n$(cat $filename.py)" > $filename.py
            # python3 $filename.py
            ipython $filename.py
          done
          ls -las
          cd -
      - name: Build Images
        run: |
          chmod +x build.sh
          ./build.sh

